### ISSUE TITLE
Touchscreen interrupt GPIO 36 does not have s/w enabled pullup

### ISSUE THREAD

**Issue by claud9999** [SolderedElectronics/Inkplate-Arduino-library#153]
Per the ESP32 documentation,

_GPI: GPIO34-39 can only be set as input mode and do not have software-enabled pullup or pulldown functions._

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/gpio.html

I believe this is why I'm seeing unreliable behavior (for example, the `Inkplate_Basic_Touchscreen_Draw` demo code reports `Touchscreen init fail` on some boots) as the touchscreen as the GPIO is "floating" (or, otherwise, if there is a pull-up resistor, the line referenced below is redundant). I'm not great with electronics design, I'm wondering if there's a simple way to solder a pull-up resistor onto some pads to always pull up GPIO36?

https://github.com/e-radionicacom/Inkplate-Arduino-library/blob/93394781b203303727c72e9e3d872dcb74a8a091/src/include/Touch.cpp#L165

**Comment by KarloLeksic** [comment]
The issue is closed because the solution is on issue #6
