### ISSUE TITLE
src/boards/Inkplate10.cpp : waveformEEPROM.waveformId read even when EEPROM is not read properly

### ISSUE THREAD

**Issue by turgu1** [SolderedElectronics/Inkplate-Arduino-library#155]
Hello all,

I'm currently updating the Inkplate10.cpp in the context of my port to ESP-IDF. In the Arduino Inkplate10.cpp source code, the waveformEEPROM.waveformId is being used, even if the waveformEEPROM has not been properly read from the EEPROM.

Guy

**Comment by KarloLeksic** [comment]
Hi,

Sorry for the late reply, we were a bit busy.

Thank you for noticing, we will check and if it is really so, it will be corrected.

**Comment by rsoric** [comment]
Closing this as there's no more activity, please reopen the issue if you think it needs more attention
