### ISSUE TITLE
Which UI library is recommend to use?

### ISSUE THREAD

**Issue by lanistor** [SolderedElectronics/Inkplate-Arduino-library#175]
It's an amazing library, we are try to use it, thanks a lot.

And, which UI library is recommend to use? LVGL or some else?

We are using LVGL with epidy(MUC: ESP32), but lvgl doesn't seem to work perfectly with ESP32([lvgl/issues/3921](https://github.com/lvgl/lvgl/issues/3921)), and the painting is slow either(nearly 2~3 seconds for full screen refresh). So we are worring about it will happen on Inkplate again.

So is there some recommend way to try?

**Comment by BornaBiro** [comment]
Hello @lanistor!

Inkplate Library at its core uses Adafruit GFX Library as a graphical library. Unfortunately, we do not have any support for LVGL or any other UI library for now.

**Comment by lanistor** [comment]
Thanks for reply.
