### ISSUE TITLE
Inkplate 6 COLOR Hardware Files

### ISSUE THREAD

**Issue by zachstence** [SolderedElectronics/Inkplate-Arduino-library#176]
I am looking for the hardware files (circuit schematics, 3D printed case) for the Inkplate 6 COLOR, but don't see them anywhere in this GitHub organization. Will they be released any time soon?

![image](https://user-images.githubusercontent.com/31896377/218298509-c33812d4-340d-4a8b-8819-18b151796c15.png)

I know this probably isn't the best place for this issue, but I wasn't sure where else it could go since the repo I'm looking for doesn't exist.

**Comment by ifadiga** [comment]
Hi,
We are going to redo all boards, incl. Inkplate 6PLUS, in KiCAD and Soldered branding, and release them here on our GitHub.

We finished all of Inkplate 10 and published the files. Also, when we finish Inkpalte 6COLOR, we will post CAD files for it here on GitHub.

On the [link ](https://github.com/SolderedElectronics/Inkplate-6-hardware/issues/5), you can download only schematics for Inkplate boards.

**Comment by KarloLeksic** [comment]
The issue is closed because there is no more activity. All files will be posted when it will be finished.
