### ISSUE TITLE
High Deep Sleep current draw for InkPlate10

### ISSUE THREAD

**Issue by K-J-Q** [SolderedElectronics/Inkplate-Arduino-library#178]
Measured the current consumption of InkPlate10 using PPK2, and got 8mA in deep sleep.... for wake on touchpad example

**Comment by ifadiga** [comment]
Can you send a picture to us to know which Inkplate10 you have?
We have old Inkplate10 (e-radionica) and Soldered Inkplate 10, and they have small differences in the hardware design. Because of that, we must know what you have that we can help you to find what is in the problem.

**Comment by K-J-Q** [comment]
Ivan,

Thanks for getting back to me. Please view the attached picture

Best Regards,
Jian Quan

**Comment by ifadiga** [comment]
Hi, 
You didn't attach a picture. Can you put it here on GitHub?

**Comment by K-J-Q** [comment]
![503B8768-F853-4C2C-B0DE-8D5915A98E24](https://user-images.githubusercontent.com/71882072/219604631-4aa6ff03-202a-41aa-a7fc-01d2f9199c46.jpeg)

**Comment by ifadiga** [comment]
I measured the current on my device, and it is 23uA in sleep. How do you measure current? Did you use a battery or USB port?

If you measure with USB then the current will be higher because the USB is connected to a USB-UART converter, which needs 7-8mA when working.

You can connect 5V to a VIN pin if you have a power supply, or you can use a battery, then the board must have a current of about 23uA.

**Comment by K-J-Q** [comment]
I have measured with the battery power as an input.

What program did you run ?

**Comment by ifadiga** [comment]
Hi,
I used the same example but added a line to isolate GPIO_12.

Can you measure current with [this](https://github.com/SolderedElectronics/Inkplate-Arduino-library/blob/master/examples/Inkplate10/Advanced_Inkplate_Features/Inkplate_Low_Power/Inkplate_Low_Power.ino)example?

**Comment by K-J-Q** [comment]
Got the desired output! thanks for your help. (connected to 3V3 pad instead of VIN)

![image](https://user-images.githubusercontent.com/71882072/220882675-46b8b395-63ee-4d21-8f08-03e1aaa25683.png)
