### ISSUE TITLE
README.md points to not maintained boards definitions repo

### ISSUE THREAD

**Issue by isk212** [SolderedElectronics/Inkplate-Arduino-library#191]
The README.md in the "Setting up Inkplate in Arduino IDE" section, first step is saying that you should install the board definitions but the link provided is targeting https://github.com/SolderedElectronics/Croduino-Board-Definitions-for-Arduino-IDE. This repo has a notice that is no longer updated and https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE should be used.

The same outdated repo is shown in the blog post linked in the "Setting up Inkplate in Arduino IDE" section.

**Comment by rsoric** [comment]
Hi @isk212 

We have updated this in a recent library release. Thanks for letting us know.

-Rob
