### ISSUE TITLE
Change pictures at WAKE button press for Image Frame examples

### ISSUE THREAD

**Issue by davidzovko** [SolderedElectronics/Inkplate-Arduino-library#192]
In Image Frame example (https://github.com/SolderedElectronics/Inkplate-Arduino-library/tree/master/examples/Inkplate6COLOR/Projects/Inkplate6COLOR_Image_Frame_From_SD), could you please add an option to change image on "WAKE" button press? The button press could wake the device from sleep, switch to next image, get back to sleep. 

Thanks :)

**Comment by KarloLeksic** [comment]
Hi @davidzovko,

Great idea, thanks for the suggestion :)
We will do it as soon as we can.

**Comment by KarloLeksic** [comment]
The issue is closed because there is no more activity. Also, an example has been made, it is just waiting for review and it will be published. It is now only available on the dev branch.
