### ISSUE TITLE
Use foreach bzw. auto loop for itterating over lists

### ISSUE THREAD

**Issue by tost11** [SolderedElectronics/Inkplate-Arduino-library#217]
for(auto ev:eventList){
        if (ev->isActive()) {
            return ev;
        }
    }

instead of

  for (int i = 0; i < eventList.size(); i++) {
    if (eventList[i]->isActive()) {
      return eventList[i];
    }
  }

**Comment by rsoric** [comment]
Hi @tost11 

Same as the smart pointers comment, internally, we prefer the classic way of writing for loops so we'll stick to doing it that way. Thanks for your input though! I hope you're enjoying making something cool with Inkplate.

-Rob
