### ISSUE TITLE
use smart pointers instead of raw pointers

### ISSUE THREAD

**Issue by tost11** [SolderedElectronics/Inkplate-Arduino-library#218]
when using smart pointers delete operation can not be forgotten so less memory leaks occur

vector<std::unique_ptr<Event>> eventList;

instead of

vector<Event*> eventList;

**Comment by rsoric** [comment]
Hi @tost11 

We didn't have plans to do this, I understand it's a good C++ practice but we prefer to use classic pointers and they are tied to our internal code standards, so we're not going to make adjustments like these any time soon.
