### ISSUE TITLE
inkplate 10 waveform sketch doesn't work correctly

### ISSUE THREAD

**Issue by nokel** [SolderedElectronics/Inkplate-Arduino-library#224]
I can type in the numbers 1 - 5 and it'll change the greyscale lines, but typing in anything else doesn't seem to make it respond?

EDIT: My issue was that I didn't realise that newline and case return weren't enabled

**Comment by rsoric** [comment]
Hi @nokel 

glad you got it sorted! I'm gonna note down that you had this issue and we can likely add it as a useful comment for other users.
