### ISSUE TITLE
Project README.md

### ISSUE THREAD

**Issue by markfodor** [SolderedElectronics/Inkplate-Arduino-library#227]
Hey!

The example projects you created are the ones people are searching for (calendar, weather station, etc). So I appreciate it a lot! 
It would be even more helpful if one could see how a project would look like on the target device.

Thanks a lot and keep up the good work!

**Comment by rsoric** [comment]
Hi @markfodor 

Thanks for your kind words, check out the 'examples' section on our official docs: https://inkplate.readthedocs.io/en/latest/examples.html

This works to get a quick overview of how the examples would work.
