### ISSUE TITLE
Inkplate6 wake up on touchpad continually firing

### ISSUE THREAD

**Issue by amcox** [SolderedElectronics/Inkplate-Arduino-library#231]
On an Inkplate6, e-radonica version, the wake on touchpad example in the Inkplate library does not work. The board continually wakes up immediately from sleep, displaying "Wakeup caused by external signal using RTC_IO".

I see the note in the example code that some boards need a pull-up resistor, and the behavior appears similar, but the link there points only to a discussion related to the Inkplate6 Color, which appears to have a different board layout.

**Comment by amcox** [comment]
Perfect, that solves the issue. Thank you very much for your help!

**Comment by rsoric** [comment]
Closing this issue as there's no more activity.
