### ISSUE TITLE
Inkplate 6" - Coil whine 

### ISSUE THREAD

**Issue by zerowriter** [SolderedElectronics/Inkplate-Arduino-library#232]
Wanted to ask if this is an issue unique to my unit or if this is behaving normally -- audible coil whine when doing a display refresh.  When running the partial refresh demo, for example, there is a constant coil whine grinding sound. I'm used to other epaper panels with no perceptible sound whatsoever.

Any ideas on troubleshooting this?

**Comment by rsoric** [comment]
Hi @zerowriter ,

great project! I have consulted with the hardware team they said that, unfortunately, the coil whine is pretty much always going to be there. It's just a part of the hardware design. If you're feeling adventurous, you can have a look at the [open source hardware files](https://github.com/SolderedElectronics/Soldered-Inkplate-6-hardware-design) to try and fix this problem.

-Rob
