### ISSUE TITLE
"Inkplate6COLOR_Hourly_Weather_Station" sketch display shows nothing after reboot.

### ISSUE THREAD

**Issue by qwertz2021** [SolderedElectronics/Inkplate-Arduino-library#244]
Hello, 

I got my Inkplate Color 6 and started to upload the "Inkplate6COLOR_Hourly_Weather_Station" arduino sketch with no modification (except lon, lat, SSID, pass and api). Compiling and uploading where successful but the display shows nothing after reboot. I tried the "Inkplate6COLOR_Daily_Weather_Station" sketch also and this works well. 

Please check!

Regrads.

**Comment by rsoric** [comment]
Hi!

Can you please check if the hourly weather station sketch is outputting anything via Serial monitor?

**Comment by rsoric** [comment]
Closing this for now as there is no more activity
